/**
 * Mock Data for Testing & Development
 * Used as fallback when backend API doesn't return data
 */

export const MOCK_THERAPISTS = [
  {
    id: "therapist-1",
    fullName: "Dr. Ayşe Yılmaz",
    email: "ayse.yilmaz@shafransa.com",
    specialization: "Fizyoterapist - Ortopedik",
    experience: 8,
    bio: "Ortopedik fizyoterapide 8 yıl deneyime sahip. Sporcu yaralanmaları ve rehabilitasyon konusunda uzmanlaşmıştır.",
    description: "Deneyimli fizyoterapist, spor yaralanmaları ve kronik ağrı yönetiminde uzmanlaşmıştır. Bireysel tedavi planları ve modern terapötik teknikler ile bütünleştirilen bir yaklaşım benimseriz.",
    avatar: "https://i.pravatar.cc/150?img=1",
    phone: "+994 12 345 67 89",
    rating: 4.8,
    reviewsCount: 127,
    reviewCount: 127,
    verified: true,
    isShowMenu: true,
    location: "Baku, Azerbaijan",
  },
  {
    id: "therapist-2",
    fullName: "Prof. Mehmet Demir",
    email: "mehmet.demir@shafransa.com",
    specialization: "Fizyoterapist - Nöroloji",
    experience: 12,
    bio: "Nörolojik fizyoterapide 12 yıl deneyim. İnme sonrası rehabilitasyon ve MS hastalığında çalışmalar.",
    description: "Nöroloji alanında deneyimli profesyonel, inme ve sinir hastalıklarında rehabilitasyon hizmeti sunan uzman terapist.",
    avatar: "https://i.pravatar.cc/150?img=2",
    phone: "+994 12 345 67 90",
    rating: 4.9,
    reviewsCount: 256,
    reviewCount: 256,
    verified: true,
    isShowMenu: true,
    location: "Baku, Azerbaijan",
  },
  {
    id: "therapist-3",
    fullName: "Zeynep Kaya",
    email: "zeynep.kaya@shafransa.com",
    specialization: "Fizyoterapist - Kardiyak",
    experience: 6,
    bio: "Kardiyak rehabilitasyon ve pulmoner fizyoterapide uzmanlaşmıştır.",
    description: "Kalp ve akciğer hastalıklarında fizyoterapeutik rehabilitasyon uzmanı olarak hizmet veren profesyonel.",
    avatar: "https://i.pravatar.cc/150?img=3",
    phone: "+994 12 345 67 91",
    rating: 4.7,
    reviewsCount: 89,
    reviewCount: 89,
    verified: true,
    isShowMenu: true,
    location: "Baku, Azerbaijan",
  },
];

export const MOCK_SESSIONS = [
  {
    id: "session-1",
    therapistId: "therapist-1",
    date: new Date(Date.now() + 86400000).toISOString(), // Tomorrow
    time: "09:00",
    duration: 60,
    status: "Available",
    price: 150,
  },
  {
    id: "session-2",
    therapistId: "therapist-1",
    date: new Date(Date.now() + 86400000).toISOString(),
    time: "10:00",
    duration: 60,
    status: "Available",
    price: 150,
  },
  {
    id: "session-3",
    therapistId: "therapist-1",
    date: new Date(Date.now() + 86400000).toISOString(),
    time: "14:00",
    duration: 60,
    status: "Available",
    price: 150,
  },
  {
    id: "session-4",
    therapistId: "therapist-1",
    date: new Date(Date.now() + 172800000).toISOString(), // Day after tomorrow
    time: "09:00",
    duration: 60,
    status: "Available",
    price: 150,
  },
  {
    id: "session-5",
    therapistId: "therapist-1",
    date: new Date(Date.now() + 172800000).toISOString(),
    time: "15:00",
    duration: 60,
    status: "Available",
    price: 150,
  },
];

export const MOCK_AVAILABILITY_SUMMARY = (() => {
  const today = new Date();
  const availableDates = [];
  
  // Generate 30 days of availability starting from tomorrow
  for (let i = 1; i <= 30; i++) {
    const date = new Date(today);
    date.setDate(date.getDate() + i);
    
    // Make 70% of days available
    const isAvailable = Math.random() > 0.3;
    
    availableDates.push({
      date: date.toISOString().split('T')[0], // YYYY-MM-DD format
      isAvailable: isAvailable,
      slots: isAvailable ? ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"] : [],
    });
  }
  
  return availableDates;
})();

export const MOCK_THERAPY_REQUESTS = [
  {
    id: "request-1",
    therapistName: "Dr. Ali Reza Mohammadi",
    specialization: "Fizyoterapist - Genel",
    experience: 5,
    bio: "Genel fizyoterapide deneyimlidir.",
    status: "Pending",
    appliedAt: new Date(Date.now() - 86400000).toISOString(),
    avatar: "https://i.pravatar.cc/150?img=4",
  },
  {
    id: "request-2",
    therapistName: "Dr. Leila Tavakkoli",
    specialization: "Fizyoterapist - Pediatrik",
    experience: 4,
    bio: "Çocuk fizyoterapisinde uzmanlaştığım.",
    status: "Pending",
    appliedAt: new Date(Date.now() - 172800000).toISOString(),
    avatar: "https://i.pravatar.cc/150?img=5",
  },
];

export const MOCK_MARKET_PRODUCTS = [
  {
    id: "seed-product-saffron-tea",
    title: "Shafransa Saffron Calm Tea",
    scientificName: "Crocus sativus",
    description: "Premium saffron tea blend for evening calm, gentle mood support, and a clean floral finish.",
    price: 24,
    originalPrice: 32,
    stock: 18,
    verified: true,
    form: "Tea",
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1544787219-7f47ccb76574?auto=format&fit=crop&w=900&q=80",
    ],
    category: { id: "seed-cat-tea", name: "Herbal Tea", slug: "herbal-tea" },
    seller: { id: "seed-seller-shafransa", fullName: "Shafransa Botanicals" },
    avgRating: 4.8,
    _count: { reviews: 42 },
    activeCompounds: "Crocin, safranal, picrocrocin",
    quality: "Lab verified, pesticide screened, small-batch packed.",
  },
  {
    id: "seed-product-lavender-oil",
    title: "Lavender Recovery Oil",
    scientificName: "Lavandula angustifolia",
    description: "Aromatic lavender oil for massage, bedtime rituals, and restorative self-care routines.",
    price: 18,
    stock: 26,
    verified: true,
    form: "Oil",
    image: "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?auto=format&fit=crop&w=900&q=80",
    ],
    category: { id: "seed-cat-oil", name: "Essential Oil", slug: "essential-oil" },
    seller: { id: "seed-seller-shafransa", fullName: "Shafransa Botanicals" },
    avgRating: 4.7,
    _count: { reviews: 31 },
    activeCompounds: "Linalool, linalyl acetate",
    quality: "Steam distilled, GC-MS checked, cosmetic grade.",
  },
  {
    id: "seed-product-turmeric-capsules",
    title: "Turmeric Joint Support Capsules",
    scientificName: "Curcuma longa",
    description: "Curcumin-rich turmeric capsules with black pepper extract for daily joint and mobility support.",
    price: 29,
    originalPrice: 36,
    stock: 34,
    verified: true,
    form: "Capsule",
    image: "https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?auto=format&fit=crop&w=900&q=80",
    images: [
      "https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?auto=format&fit=crop&w=900&q=80",
      "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=900&q=80",
    ],
    category: { id: "seed-cat-capsule", name: "Capsules", slug: "capsules" },
    seller: { id: "seed-seller-shafransa", fullName: "Shafransa Botanicals" },
    avgRating: 4.9,
    _count: { reviews: 58 },
    activeCompounds: "Curcuminoids, piperine",
    quality: "Heavy metal screened, vegan capsules.",
  },
  {
    id: "seed-product-ginger-extract",
    title: "Ginger Digestive Extract",
    scientificName: "Zingiber officinale",
    description: "Concentrated ginger extract for digestive comfort, travel support, and warming daily rituals.",
    price: 21,
    stock: 22,
    verified: true,
    form: "Extract",
    image: "https://assets.epicurious.com/photos/58d3fed8e2c8295cfbf4a52f/16:9/w_2560%2Cc_limit/ginger_root_pile_23032017.jpg",
    images: [
      "https://assets.epicurious.com/photos/58d3fed8e2c8295cfbf4a52f/16:9/w_2560%2Cc_limit/ginger_root_pile_23032017.jpg",
      "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?auto=format&fit=crop&w=900&q=80",
    ],
    category: { id: "seed-cat-extract", name: "Extracts", slug: "extracts" },
    seller: { id: "seed-seller-shafransa", fullName: "Shafransa Botanicals" },
    avgRating: 4.6,
    _count: { reviews: 27 },
    activeCompounds: "Gingerols, shogaols",
    quality: "Standardized liquid extract, alcohol-free.",
  },
];

export const MOCK_ENCYCLOPEDIA_PLANTS = [
  {
    id: "seed-herb-saffron",
    name: "Saffron",
    scientificName: "Crocus sativus",
    localName: "Zəfəran",
    shortSummary: "Saffron is a high-value botanical traditionally used for mood, calm, and culinary wellness.",
    description: "Saffron is the dried stigma of Crocus sativus. It is valued for its aroma, vivid color, and traditional use in emotional balance and restorative rituals.",
    benefits: "Traditionally used for mood support, relaxation, antioxidant activity, and gentle digestive comfort.",
    usage: "Used as tea, culinary infusion, or standardized extract in low amounts.",
    dosage: "Tea infusion: a few strands in warm water. Extracts should follow product guidance.",
    activeCompounds: "Crocin, crocetin, safranal, picrocrocin",
    contraindications: "Avoid high doses during pregnancy. Use caution with mood medications.",
    sideEffects: "High amounts may cause dizziness, nausea, or headache.",
    drugInteractions: "May interact with sedatives, antidepressants, or blood pressure medication.",
    pregnancyWarnings: "Avoid medicinal doses during pregnancy and nursing unless clinician approved.",
    evidenceGrade: "B",
    continent: "Asia",
    region: "Azerbaijan, Iran, Mediterranean",
    terroir: "Dry sunny fields with well-drained soil",
    wildCultivated: "Cultivated",
    chemotype: "Crocin-rich",
    climate: "Semi-arid to Mediterranean climate.",
    image: "https://upload.wikimedia.org/wikipedia/commons/6/68/Saffron_-_premium_spice.jpg",
    products: [MOCK_MARKET_PRODUCTS[0]],
  },
  {
    id: "seed-herb-lavender",
    name: "Lavender",
    scientificName: "Lavandula angustifolia",
    localName: "Lavanda",
    shortSummary: "Lavender is an aromatic herb widely used for calm, sleep rituals, and topical comfort.",
    description: "Lavender contains fragrant volatile oils and is used in aromatherapy, massage oils, teas, and topical preparations.",
    benefits: "Traditionally used for relaxation, sleep hygiene, mild tension, and skin comfort.",
    usage: "Used as essential oil, tea, bath preparation, or topical diluted oil.",
    dosage: "Essential oil should be diluted before topical use. Tea products should follow label guidance.",
    activeCompounds: "Linalool, linalyl acetate, lavandulol",
    contraindications: "Avoid undiluted essential oil on skin. Use caution with sedative medicines.",
    sideEffects: "Skin irritation may occur in sensitive users.",
    drugInteractions: "May increase sedation when combined with sedatives.",
    pregnancyWarnings: "Use medicinal preparations cautiously during pregnancy.",
    evidenceGrade: "B",
    continent: "Europe",
    region: "Mediterranean",
    terroir: "Sunny rocky fields",
    wildCultivated: "Cultivated",
    chemotype: "Linalool-rich",
    climate: "Mediterranean and temperate dry climates.",
    image: "https://images.unsplash.com/photo-1499002238440-d264edd596ec?auto=format&fit=crop&w=900&q=80",
    products: [MOCK_MARKET_PRODUCTS[1]],
  },
  {
    id: "seed-herb-turmeric",
    name: "Turmeric",
    scientificName: "Curcuma longa",
    localName: "Sarıkök",
    shortSummary: "Turmeric is a golden rhizome known for curcuminoids and traditional joint support.",
    description: "Turmeric is a rhizome used in food and herbal preparations. Curcuminoids are the best-known compounds.",
    benefits: "Traditionally used for joint comfort, antioxidant support, digestion, and healthy inflammatory balance.",
    usage: "Used as powder, capsules, extracts, and culinary spice.",
    dosage: "Capsules and extracts should follow label guidance, especially when combined with piperine.",
    activeCompounds: "Curcumin, demethoxycurcumin, bisdemethoxycurcumin",
    contraindications: "Use caution with gallbladder disease, anticoagulants, or upcoming surgery.",
    sideEffects: "May cause digestive upset in some users.",
    drugInteractions: "May interact with anticoagulants and antiplatelet drugs.",
    pregnancyWarnings: "Food amounts are typical; medicinal doses need clinician guidance.",
    evidenceGrade: "A",
    continent: "Asia",
    region: "India, Southeast Asia",
    terroir: "Humid tropical soil",
    wildCultivated: "Cultivated",
    chemotype: "Curcuminoid-rich",
    climate: "Warm humid tropical climate.",
    image: "https://images.unsplash.com/photo-1615485925600-97237c4fc1ec?auto=format&fit=crop&w=900&q=80",
    products: [MOCK_MARKET_PRODUCTS[2]],
  },
  {
    id: "seed-herb-ginger",
    name: "Ginger",
    scientificName: "Zingiber officinale",
    localName: "Zəncəfil",
    shortSummary: "Ginger is a warming rhizome traditionally used for digestion and travel comfort.",
    description: "Ginger is used as food, tea, extract, and powder. Its pungent compounds support traditional digestive applications.",
    benefits: "Traditionally used for nausea, digestive comfort, warming circulation, and cold-season rituals.",
    usage: "Used as fresh root, tea, extract, capsule, or culinary spice.",
    dosage: "Tea and extracts should follow product guidance; sensitive users should start low.",
    activeCompounds: "Gingerols, shogaols, zingerone",
    contraindications: "Use caution with anticoagulants or gallbladder conditions.",
    sideEffects: "May cause heartburn or stomach warmth in sensitive users.",
    drugInteractions: "May interact with blood thinners and diabetes medication.",
    pregnancyWarnings: "Often used for nausea, but medicinal use should be clinician guided.",
    evidenceGrade: "A",
    continent: "Asia",
    region: "South Asia, Southeast Asia",
    terroir: "Moist tropical soil",
    wildCultivated: "Cultivated",
    chemotype: "Gingerol-rich",
    climate: "Warm humid climate.",
    image: "https://assets.epicurious.com/photos/58d3fed8e2c8295cfbf4a52f/16:9/w_2560%2Cc_limit/ginger_root_pile_23032017.jpg",
    products: [MOCK_MARKET_PRODUCTS[3]],
  },
];
