name: Deploy React App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SERVER_SSH_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'

          echo "=== FIX GITHUB SSH ==="
          ssh-keyscan -H github.com >> ~/.ssh/known_hosts

          echo "=== INSTALL NODE ==="
          apt update
          apt install -y curl git nginx
          curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
          apt install -y nodejs

          echo "=== CLEAN OLD APP ==="
          rm -rf /var/www/shafransa
          mkdir -p /var/www/shafransa
          cd /var/www/shafransa

          echo "=== CLONE PROJECT ==="
          git clone git@github.com:ZakirAliyev/shafransa.git .

          echo "=== INSTALL & BUILD ==="
          npm install
          npm run build

          echo "=== DEPLOY TO NGINX ==="
          rm -rf /var/www/html/*

          if [ -d "dist" ]; then
            cp -r dist/* /var/www/html/
          elif [ -d "build" ]; then
            cp -r build/* /var/www/html/
          else
            echo "Build folder yoxdur!"
            exit 1
          fi

          systemctl restart nginx

          echo "=== DONE ==="

          EOF
