name: Build & Deploy React App

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Repo çek
      - name: Checkout
        uses: actions/checkout@v4

      # Node setup
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install & build
      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # SSH setup
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf "%s" "${{ secrets.SERVER_SSH_KEY_BASE64 }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      # Deploy (DIST GÖNDƏRİLİR)
      - name: Deploy to Server
        run: |
          scp -r dist/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/
